name: Refresh Amazon Canada deals

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Amazon Canada feed
        env:
          PAAPI_CLIENT_ID: ${{ secrets.PAAPI_CLIENT_ID }}
          PAAPI_CLIENT_SECRET: ${{ secrets.PAAPI_CLIENT_SECRET }}
          PAAPI_ASSOCIATE_TAG: ${{ secrets.PAAPI_ASSOCIATE_TAG }}
        run: |
          python admin/amazon_paapi_daily.py --limit 8

      - name: Run smoke tests
        run: python -m unittest tests.test_amazon_paapi_daily

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh Amazon Canada deals"
          file_pattern: data/amazon_ca_daily.json
