name: Daily Amazon Deals

on:
  schedule:
    - cron: '30 9 * * *'
  workflow_dispatch:

jobs:
  fetch-deals:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Amazon deals dataset
        env:
          PAAPI_CLIENT_ID: ${{ secrets.PAAPI_CLIENT_ID }}
          PAAPI_CLIENT_SECRET: ${{ secrets.PAAPI_CLIENT_SECRET }}
          PAAPI_ASSOCIATE_TAG: ${{ secrets.PAAPI_ASSOCIATE_TAG }}
        run: |
          python admin/amazon_paapi_daily.py --limit 8

      - name: Commit updated dataset
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Amazon deals feed"
          file_pattern: data/amazon_ca_daily.json
