name: Canadian Tire clearance scraper

on:
  schedule:
    # 04:00 America/Toronto ≈ 09:00 UTC (08:00 during DST)
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      comment:
        description: "Note facultative pour cette exécution"
        required: false
        type: string

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Canadian Tire scraper
        run: python incoming/canadian_tire_scraper.py

      - name: Upload liquidation reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: canadian-tire-liquidations-${{ github.run_id }}
          path: |
            liquidations_canadian_tire_qc.json
            data/canadian-tire/*.json
          if-no-files-found: warn
