name: Rona St-Jérôme Daily Scraper

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  rona_scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install

      - name: Run Playwright scraper
        run: python scraper_rona_playwright.py

      - name: Commit and push JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add rona-st-jerome.json
          git commit -m "Mise à jour des données liquidation RONA" || echo "No changes to commit"
          git push
