name: Manual Sporting Life Scraper

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL de la page liquidation à scruter"
        required: true
        default: "https://www.sportinglife.ca/fr-CA/liquidation/"
      max_retries:
        description: "Nombre maximal de tentatives Playwright"
        required: false
        default: "3"
      retry_delay:
        description: "Délai entre les tentatives (secondes)"
        required: false
        default: "5"
      page_timeout:
        description: "Timeout de chargement de page (ms)"
        required: false
        default: "60000"
      wait_timeout:
        description: "Timeout des éléments (ms)"
        required: false
        default: "30000"
      headless:
        description: "Exécuter Playwright en mode headless (true/false)"
        required: false
        default: "true"
      log_level:
        description: "Niveau de log du scraper"
        required: false
        default: "INFO"
      dry_run:
        description: "Ne pas envoyer vers l'API EconoDeal (true/false)"
        required: false
        default: "true"
      api_url:
        description: "URL de l'API EconoDeal pour l'import"
        required: false
        default: "https://www.econodeal.ca/api/import_liquidation"
      json_path:
        description: "Chemin de sortie JSON"
        required: false
        default: "output/liquidations_sportinglife.json"
      log_path:
        description: "Chemin du fichier log"
        required: false
        default: "output/sportinglife_scraper.log"

permissions:
  contents: read

jobs:
  debug-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "url=${{ github.event.inputs.url }}"
          echo "max_retries=${{ github.event.inputs.max_retries }}"
          echo "headless=${{ github.event.inputs.headless }}"

  run-scraper:
    needs: debug-inputs
    name: Exécuter le scraper Sporting Life
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers
        run: python -m playwright install chromium

      - name: Run Sporting Life scraper
        env:
          SPORTINGLIFE_API_TOKEN: ${{ secrets.SPORTINGLIFE_API_TOKEN }}
        run: |
          set -euo pipefail
          JSON_PATH="${{ inputs.json_path }}"
          LOG_PATH="${{ inputs.log_path }}"
          mkdir -p "$(dirname "$JSON_PATH")"
          mkdir -p "$(dirname "$LOG_PATH")"
          MAX_RETRIES=$(( ${{ inputs.max_retries }} + 0 ))
          RETRY_DELAY=$(( ${{ inputs.retry_delay }} + 0 ))
          PAGE_TIMEOUT=$(( ${{ inputs.page_timeout }} + 0 ))
          WAIT_TIMEOUT=$(( ${{ inputs.wait_timeout }} + 0 ))
          EXTRA_ARGS=(
            --url "${{ inputs.url }}"
            --max-retries "$MAX_RETRIES"
            --retry-delay "$RETRY_DELAY"
            --page-timeout "$PAGE_TIMEOUT"
            --wait-timeout "$WAIT_TIMEOUT"
            --log-level "${{ inputs.log_level }}"
            --api-url "${{ inputs.api_url }}"
          )
          if [ "${{ inputs.headless }}" != "true" ]; then
            EXTRA_ARGS+=(--no-headless)
          fi
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            EXTRA_ARGS+=(--skip-upload)
          fi
          python admin/sportinglife_liquidations.py \
            --output "$JSON_PATH" \
            --log-file "$LOG_PATH" \
            "${EXTRA_ARGS[@]}"

      - name: Upload scraper artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sportinglife-scraper-output
          path: |
            ${{ inputs.json_path }}
            ${{ inputs.log_path }}
          if-no-files-found: error
